--BASE DE DATOS RETO
DROP DATABASE IF EXISTS DonostiaKultura;
CREATE DATABASE DonostiaKultura;
USE DonostiaKultura;

CREATE TABLE Users (
DNI VARCHAR(9) PRIMARY KEY,
Name VARCHAR(50) NOT NULL,
Rol VARCHAR(100) NOT NULL,
Surname VARCHAR(100) NOT NULL,
Email VARCHAR(255) NOT NULL,
Password VARCHAR(255) NOT NULL,
PhoneNumber VARCHAR(50) 
);

CREATE TABLE Suggestions (
SuggestionID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Description TINYTEXT NOT NULL,
UserName VARCHAR(50) NOT NULL,
UserEmail VARCHAR(255) NOT NULL,
SuggestionDate  DATE,
FOREIGN KEY (UserName) REFERENCES Users(Name),
FOREIGN KEY (UserEmail) REFERENCES Users(Email)

);

CREATE TABLE Formations (
FormationID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY ,
Name VARCHAR(50),
Description TINYTEXT,
Peculiarity ENUM('English',NULL)
);

CREATE TABLE Companys (
CIF VARCHAR(20) PRIMARY KEY,
Name VARCHAR(50) NOT NULL,
Address VARCHAR(255) NOT NULL
);



CREATE TABLE Sessions (
SessionID INT PRIMARY KEY,
Day DATE,
Hour Date,
Capacity INT UNSIGNED,
FormationID INT UNSIGNED,
CompanyName VARCHAR(50)
);

CREATE TABLE Reservations (
ReservationID INT UNSIGNED PRIMARY KEY,
UserID VARCHAR(9) NOT NULL,
SessionID INT
);

CREATE TABLE DeleteLogs (
ActionID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
AffectedTable VARCHAR(50),
DataBeforeDelete TINYTEXT,
DeleteDate DATE

);


CREATE TABLE UpdateLogs (
ActionID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
AffectedTable VARCHAR(50),
DataBeforeUpdate TINYTEXT,
DeleteDate DATE
);